### ISSUE TITLE
How to run demo "locally?"

### ISSUE THREAD

**Issue by olyerickson** [mpoegel/SemNExT-Visualizations#26]
How can we make this run locally? 

I've followed the instructions at

https://github.com/mpoegel/SemNExT-Visualizations

...including satisfying all of the dependencies (took a couple iterations!), but I got lost at "Set the app configuration" and thus it crapped out when I attempted to "run" it with gulp.

I think I'm missing a bit of context...I'm close, but missing something.

**Comment by mpoegel** [comment]
Apologies for not being more clear. What that means is to create a file named in the `src` folder with the name `config.json` with the following content.
```json
{
  "port": 8000
}
```
Then you should be able to start the application with `gulp`, which will be available at localhost:8000.

The idea behind this was that I thought I would need more configuration options in the future, but that hasn't been the case so far. I will probably change this to just setting an environment variable in the future.

**Comment by olyerickson** [comment]
That made a little progress...When attempting to `gulp` I now see:

```
$ gulp
[10:52:11] Using gulpfile ~/Desktop/SemNExT-Visualizations/gulpfile.js
[10:52:11] Starting 'watch'...
[10:52:11] Finished 'watch' after 26 ms
[10:52:11] Starting 'nodemon'...
[10:52:11] Finished 'nodemon' after 62 ms
[10:52:11] Starting 'default'...
[10:52:11] Finished 'default' after 10 μs
[10:52:11] [nodemon] 1.11.0
[10:52:11] [nodemon] to restart at any time, enter `rs`
[10:52:11] [nodemon] watching: *.*
[10:52:11] [nodemon] starting `node ./src/server.js`
module.js:328
    throw err;
    ^

Error: Cannot find module '/home/olyerickson/Desktop/SemNExT-Visualizations/src/server.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
[10:52:11] [nodemon] app crashed - waiting for file changes before starting...
```

It is correct, there is no `server.js` file...

**Comment by olyerickson** [comment]
When I go back to `npm install` I see the following:

```
$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
```
Digging in:
```
 $ sudo npm install fsevents
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "fsevents"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.17
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/olyerickson/Desktop/SemNExT-Visualizations/npm-debug.log
```

Does this mean this demo can't be run on Linux?????

**Comment by olyerickson** [comment]
It turns out that `fsevents` is an optional dependency only required for MacOS. 

So install should probably be done with `--no-optional` on...

**Comment by mpoegel** [comment]
There was a small bug in the gulpfile that didn't redirect the compiled typescript back into the `src` folder. I pushed a patch to master to fix it.

**Comment by olyerickson** [comment]
That worked! Note that I needed to re-bundle but otherwise that was all that was required. 

![selection_023](https://cloud.githubusercontent.com/assets/358649/23083170/896bd096-f52a-11e6-9e55-bcf7a76f3eb4.png)
